[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/pdf-parse/lib/**", "node_modules/pdf-parse/index.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
